services:
  # Build locally
  app:
    build: ./app/.
    image: lineloginmicroservice-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - "./docker/app/db:/db"
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
        - action: rebuild
          path: ./app

    